# Generated by Django 3.2.4 on 2024-07-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_loans', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_repayments', models.DecimalField(decimal_places=2, max_digits=15)),
                ('outstanding_loans', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
