version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8765
    volumes:
      - .:/code
    ports:
      - "8765:8765"
    depends_on:
      - redis
      - celery
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  redis:
    image: redis:6.0

  celery:
    build: .
    command: celery -A finanzy worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  celery-beat:
    build: .
    command: celery -A finanzy beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

volumes:
  postgres-data:
