# docker-compose.yml

version: '3.8'

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8765
    volumes:
      - .:/code
    ports:
      - "8765:8765"
    depends_on:
      - redis
      - celery

  redis:
    image: redis:6.0

  celery:
    build: .
    command: celery -A finanzy worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A finanzy beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
